#7 Create a module for rewards
kommitters/mtk-automation pull request #10
Opened 2023-02-15 14:00 UTC by Jenietoc

## Description

In this PR we created the rewards module and the validations module for the contract.

Fixes #7 

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented on my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings

2023-02-15 14:07 UTC, L-Zuluaga requested changes
I left an small suggestion, apart from that it LGTM!

2023-02-15 14:07 UTC, L-Zuluaga commented on mtk-automation/src/contract_actions/reward.rs
> +fn transfer(env: &Env, approval_sign: &Signature, to: &Identifier, amount: &i128) {
What do you think about moving this function into a new module called for example `token_operations` where we could group all the functions that interact with the token contract?

2023-02-15 14:16 UTC, L-Zuluaga commented on mtk-automation/src/contract_actions/reward.rs
> +fn transfer(env: &Env, approval_sign: &Signature, to: &Identifier, amount: &i128) {
@Jenietoc we also need to replace the `reward` word with `compensation`, which is a more accurate word for this context

2023-02-15 21:28 UTC, L-Zuluaga requested changes
Left a couple of comments

2023-02-15 21:28 UTC, L-Zuluaga commented on mtk-automation/src/contract_actions/datakey.rs
> +    Compensate,
A better word here could be `Compensations`?

2023-02-15 21:28 UTC, L-Zuluaga commented on mtk-automation/src/contract_actions/compensate.rs
> +//! Compensate Module
I'm not sure if  `Compensations` could be a better name for this Module? 🤔 
What do you think @einerzg @Jenietoc?

2023-02-15 21:33 UTC, Jenietoc commented on mtk-automation/src/contract_actions/datakey.rs
> +    Compensate,
I can only use 10 characters :sweat_smile:

2023-02-15 21:33 UTC, Jenietoc commented on mtk-automation/src/contract_actions/compensate.rs
> +//! Compensate Module
:eyes: :eyes:

2023-02-16 13:27 UTC, L-Zuluaga commented on mtk-automation/src/contract_actions/datakey.rs
> +    Compensate,
Hmm thats true, then I think it makes sense to keep it like this, anyway I'll think on a different word to refer to this part 🤔

2023-02-16 15:56 UTC, Odraxs commented on mtk-automation/src/contract_actions/datakey.rs
> +    Compensate,
@L-Zuluaga @einerzg WDYT about renaming `Compensations` to `Perks` ? :thinking:

2023-02-16 21:35 UTC, einerzg commented on mtk-automation/src/contract_actions/datakey.rs
> +    Compensate,
@Odraxs I think `Perk` does not represent what is really being done, I prefer `Payments`.

2023-02-16 22:43 UTC, L-Zuluaga approved these changes

2023-02-17 16:04 UTC, einerzg approved these changes

2023-02-17 16:23 UTC, merged