Add test to contract
kommitters/mtk-automation pull request #20
Opened 2023-02-20 15:25 UTC by Odraxs

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-02-20 23:52 UTC, Odraxs commented
Probably we need to define how to call the function that gives the `compensation`/`rewards` so we can define how to rename  `reward_m` and `c_type`/`r_type` better

2023-02-21 14:54 UTC, L-Zuluaga requested changes

2023-02-21 14:54 UTC, L-Zuluaga commented on mtk-automation/src/lib.rs
> +    fn fund_c(env: Env, approval_address: Address);
What do you think about using `admin_address` instead?

2023-02-21 14:54 UTC, L-Zuluaga commented on mtk-automation/src/contract_actions/reward.rs
> +pub fn set_rewards(env: &Env, compensate_types: &Map<Symbol, i32>) {
I think we can follow @einerzg suggestion and use the word **offset** for naming this, so we can put everything in those terms like:
`set_offsets`, `offset_a_member`, `is_offset_valid`, etc

What do you think? 🤔

2023-02-21 22:17 UTC, L-Zuluaga approved these changes
LGTM! Excelent job 🚀 
I left a small comment just in case you want to take it into account :)

2023-02-21 22:17 UTC, L-Zuluaga commented on mtk-automation/src/contract_actions/offset.rs
> +pub fn offset_member(env: &Env, admin_address: &Address, to: &Address, offset_type: &Symbol) {
Maybe `offset_a_member` describes better what the function does?

2023-02-22 03:10 UTC, einerzg requested changes
Checking the coverage I get that these two (`revoke_m` & `get_tc_id`) functions were not covered. Please check. 
<img width="815" alt="Screen Shot 2023-02-21 at 10 02 43 PM" src="https://user-images.githubusercontent.com/2568221/220510559-4a78cd0c-8c2a-4068-a9ca-7ee84c1f5656.png">

Ideal to have the coverage at 100% is now at 77.57%.

2023-02-22 13:38 UTC, Odraxs commented
> Checking the coverage I get that these two (`revoke_m` & `get_tc_id`) functions were not covered. Please check. <img alt="Screen Shot 2023-02-21 at 10 02 43 PM" width="815" src="https://user-images.githubusercontent.com/2568221/220510559-4a78cd0c-8c2a-4068-a9ca-7ee84c1f5656.png">
> 
> Ideal to have the coverage at 100% is now at 77.57%.

@einerzg Sure we can test `get_tc_id`, but `revoke_m` is not possible right now because it has a `todo!` which works like a `panic!` that gives a reminder of a not fully implemented functionality

2023-02-22 20:06 UTC, L-Zuluaga submitted a review, later dismissed
Everything LGTM, I left a small comment in case you want to take it into account

2023-02-22 20:06 UTC, L-Zuluaga commented on mtk-automation/src/test.rs
> +fn happy_path() {
What do you think about changing this name for something like: **succesfully_add_and_offset_a_member** or something that desribes better what we are testing in this specific case? 🤔

2023-02-22 20:22 UTC, Odraxs commented on mtk-automation/src/test.rs
> +fn happy_path() {
@L-Zuluaga sounds good at least until the swap functionality is fully implemented and we will want to test revoke there, I'm changing it to the suggested name until that implementation

2023-02-22 21:33 UTC, L-Zuluaga approved these changes

2023-02-23 16:40 UTC, einerzg approved these changes

2023-02-23 16:43 UTC, merged