Create new validations for admin
kommitters/mtk-automation pull request #25
Opened 2023-02-24 19:31 UTC by Jenietoc

## Description

Added validations at the moment of adding and deleting members.

Fixes #22 

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] My changes generate no new warnings

2023-02-24 20:32 UTC, Odraxs requested changes

2023-02-24 20:32 UTC, Odraxs commented on mtk-automation/src/contract_actions/member.rs
> +    if is_member(env, &member) {panic!("Member Already exists")};
@Jenietoc  Is this code well formatted?
pls run `cargo fmt` to ensure it is well formatted
@L-Zuluaga  I think we need to add `cargo fmt --check` to the CI file

2023-02-24 20:49 UTC, L-Zuluaga requested changes

2023-02-24 20:49 UTC, L-Zuluaga commented on mtk-automation/src/contract_actions/member.rs
> +pub(crate) fn add_member(env: &Env, member: Address, admin: Address) {
You are receiving the admin as an address, but we could use the env.invoker() function. However, that function was removed on the latest version, so I think we should use the new approach, which required to include the address as a param WITH some additional steps.

Take a look at this and check if it make sense: https://soroban.stellar.org/docs/how-to-guides/auth-migration#migrating-envinvoker
![image](https://user-images.githubusercontent.com/32212593/221288537-bc107b8a-dd28-4ef7-9be6-545b4f17ed69.png)

2023-02-24 21:39 UTC, Jenietoc commented on mtk-automation/src/contract_actions/admin.rs
> +        panic!("Not authorized by admin")
**Not Authorized** looking good

2023-02-27 16:56 UTC, L-Zuluaga requested changes

2023-02-27 16:56 UTC, L-Zuluaga commented on .github/workflows/cd.yaml
> +          --network-passphrase 'Test SDF Future Network ; October 2022'
include here the EOL

2023-02-27 21:53 UTC, L-Zuluaga approved these changes
LGTM
@einerzg if you can give it a look just in case would be awesome!

2023-02-28 14:44 UTC, einerzg approved these changes

2023-02-28 14:46 UTC, Odraxs approved these changes

2023-02-28 14:47 UTC, merged