Prepare release v0.2.0
kommitters/mtk-automation pull request #35
Opened 2023-03-01 15:14 UTC by Odraxs

2023-03-01 15:54 UTC, L-Zuluaga requested changes
Left some questions and suggestions, reach me out if there are any doubts about them

2023-03-01 15:54 UTC, L-Zuluaga commented on README.md
> +4. Generate a signature to fund the organization's token balance using the administrator's account.
Are we still using that signature? or are we just using the admin Address instead?

2023-03-01 15:54 UTC, L-Zuluaga commented on README.md
> +4. Initialize the organization contract with your custom rewards.
```suggestion
4. Initialize the organization contract with your custom offsets.
```

2023-03-01 15:54 UTC, L-Zuluaga commented on README.md
> +1. Approve the transaction using the token contract.
Are we still using that approve?

2023-03-01 15:54 UTC, L-Zuluaga commented on README.md
> +3. Initialize the organization contract with your custom rewards.
```suggestion
3. Initialize the organization contract with your custom offsets.
```

2023-03-01 15:54 UTC, L-Zuluaga commented on README.md
> +8. Reward members.
```suggestion
8. Offset members.
```

2023-03-01 15:54 UTC, L-Zuluaga commented on README.md
> +> **Note** Signatures are required to execute any functions involving calls to **privileged functions** of the token contract. [Token Contract Interface](https://soroban.stellar.org/docs/common-inter
I'm not sure if this is still applicable, since the signature now is the admin Address, maybe we could explain this part in a different way, what do you think?

2023-03-01 15:54 UTC, L-Zuluaga commented on README.md
> +#### **token_exchange**
what do you think about this suggestion to make it a bit more descriptive? 🤔 
```suggestion
#### **token_exchange contract**
```

2023-03-01 15:54 UTC, L-Zuluaga commented on README.md
> +#### **mtk_automation**
Same suggestion as above if you agree

2023-03-01 16:06 UTC, Odraxs commented on README.md
> +4. Generate a signature to fund the organization's token balance using the administrator's account.
@L-Zuluaga 
This was in the "main" branch, so I didn't read it thoroughly however, I will read it and modify it with the current implementation.

2023-03-01 16:23 UTC, Odraxs commented on README.md
> +1. Approve the transaction using the token contract.
@L-Zuluaga well, this is now "approved" by the `exchange_contract` in some way or WDYT?

2023-03-02 15:59 UTC, einerzg requested changes

2023-03-02 15:59 UTC, einerzg commented on README.md
> +5. Initialize the `token_exchange` contract with your exchange tokens(those you created in step `#2`) and exchange prices.
there are 2 `5`

2023-03-02 15:59 UTC, einerzg commented on README.md
> +    --fn revoke_m1 \
`revoke_s1`

2023-03-02 15:59 UTC, einerzg commented on README.md
> +    --fn revoke_m2 \
`revoke_s2`

2023-03-02 15:59 UTC, einerzg commented on README.md
> +    --fn revoke_m3 \
`revoke_s3`

2023-03-02 15:59 UTC, einerzg commented on README.md
> +    --fn revoke_m3 \
the description of what each stage is used for is added

2023-03-03 15:41 UTC, einerzg approved these changes

2023-03-03 19:38 UTC, einerzg approved these changes

2023-03-03 19:44 UTC, L-Zuluaga approved these changes

2023-03-03 19:45 UTC, merged