#5 Create module for members
kommitters/mtk-automation pull request #9
Opened 2023-02-10 18:58 UTC by Jenietoc

## Description

In this PR we created the `members` module for the management of adding, deleting and obtaining members of the organization. We also created modules necessary for the perfect functioning of the module. The `soroban_sdk` was updated to version `0.4.3`.

Fixes #5 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-02-10 20:07 UTC, einerzg requested changes
@Jenietoc, please check the comments and add the test!!!

2023-02-10 20:07 UTC, einerzg commented on mtk-automation/src/modules/member.rs
> +        );
Please extract this code in another function!!!!

2023-02-10 20:07 UTC, einerzg commented on mtk-automation/src/modules/member.rs
> +        );
It's pending to add a swapping here!!! Please add a `todo`.

2023-02-10 21:22 UTC, L-Zuluaga requested changes

2023-02-13 15:34 UTC, Jenietoc commented on mtk-automation/Cargo.toml
> +name = "return-funds-on-leaving"
Already corrected it

2023-02-13 21:01 UTC, einerzg requested changes
@Jenietoc, please review new comments!!!

2023-02-13 21:21 UTC, Odraxs commented on mtk-automation/src/contract_actions/member.rs
> +    pub fn get_members<T: soroban_sdk::TryFromVal<Env, RawVal> + soroban_sdk::IntoVal<Env, RawVal>>(
Yes, we need it in `lib.rs` line `57`

2023-02-14 21:11 UTC, Odraxs approved these changes

2023-02-14 23:11 UTC, einerzg approved these changes
LGTM!!!

2023-02-15 13:29 UTC, L-Zuluaga approved these changes
LGTM! excellent job 🚀

2023-02-15 13:46 UTC, merged